security:
    encoders:
        App\Entity\User:
            algorithm: auto
    providers:
        user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: user_provider
            user_checker: App\Security\UserChecker\UserChecker
            guard:
                authenticators:
                    - App\Security\Guard\WebAuthenticator
            logout:
                path: security_logout
    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
