security:
    encoders:
        App\Infrastructure\Symfony\Security\SecurityUser:
            algorithm: auto
    providers:
        user_provider:
            id: App\Infrastructure\Symfony\Security\Provider\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: user_provider
#            user_checker: App\Infrastructure\Symfony\Security\UserChecker\UserChecker
            guard:
                authenticators:
                    - App\Infrastructure\Symfony\Security\Guard\WebAuthenticator
            logout:
                path: security_logout
    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
