parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
    App\Infrastructure\Symfony\Controller\:
        resource: '../src/Infrastructure/Symfony/Controller/'
        tags: ['controller.service_arguments']
    App\Domain\User\UserInterface\Action\:
        resource: '../src/Domain/User/UserInterface/Action/'
        tags: ['controller.service_arguments']